### ISSUE TITLE
Using Only NLog.config for RichTextBox Does Not Log

### ISSUE THREAD

**Issue by JoeCode20** [NLog/NLog.Windows.Forms#120]
Hello! I'm trying to log to a RichTextBox by setting up my logger only through the NLog.config file by trying to run the RichTextBox.sln with the following lines commented out of Form1.cs

```c#
private void Form1_Load(object sender, EventArgs e)
        {
            // Programmatic configuration that is equivalent to
            // the "richTextBox" target configuration in NLog.config
            //RichTextBoxTarget target = new RichTextBoxTarget();
            //target.Layout = "${date:format=HH\\:MM\\:ss} ${logger} ${message}";
            //target.ControlName = "richTextBox1";
            //target.FormName = "Form1";
            //target.UseDefaultRowColoringRules = true;

            //NLog.Config.SimpleConfigurator.ConfigureForTargetLogging(target, LogLevel.Trace);

            Logger logger = LogManager.GetLogger("Example");
            logger.Trace("trace log message");
            logger.Debug("debug log message");
            logger.Info("info log message");
            logger.Warn("warn log message");
            logger.Error("error log message");
            logger.Fatal("fatal log message");
        }`
```
If I'm understanding correctly, commenting out the top-half of this method should prevent the NLog.config from being overwritten by the new programmatically defined config. However, the outcome of this (at least on my system) is that nothing shows up in the RichTextBox at all. These comments are the only changes I've made to the code, otherwise it is exactly the same as what's in the master branch. Can RichTextBoxTarget only be setup programmatically? If you need any more information, let me know. 

Thank you!

**Comment by 304NotModified** [comment]
Yes, everything could be setup from config. Please check 
https://github.com/nlog/nlog/wiki/Logging-troubleshooting

**Comment by JoeCode20** [comment]
I took a look at that wiki article and it was a great starting point. I changed the NLog.config Property "Copy to Output Directory" to "Copy if newer" and it seems to be working just fine. Sorry about the confusion and thank you for helping :)

**Comment by 304NotModified** [comment]
I'm glad is has been resolved 👍
