### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by dguder** [NLog/NLog.Windows.Forms#2]
Hi, I'm testing NLog to replace a self written log engine and wanted to use NLog.Windows.Forms. But I'm a little bit confused about its license: 
**NLog** is [BSD](https://github.com/NLog/NLog/blob/master/LICENSE.txt) licenses. But **NLog.Windows.Forms** is licensed under [GPLv2](https://github.com/NLog/NLog.Windows.Forms/blob/master/LICENSE). But some source files like [`FormControlTarget.cs`](https://github.com/NLog/NLog.Windows.Forms/blob/master/NLog.Windows.Forms/FormControlTarget.cs) and [`FormHelper.cs`](https://github.com/NLog/NLog.Windows.Forms/blob/master/NLog.Windows.Forms/FormHelper.cs) are [ALv2](http://www.apache.org/licenses/LICENSE-2.0) licensed.
It would be nice if you can make the licenses consistent. Ideally for me change it to BSD as at NLog.

**Comment by 304NotModified** [comment]
GPL is wrong - I hope. We will look at this

**Comment by 304NotModified** [comment]
It's BSD. We will update the inconsistencies

**Comment by dguder** [comment]
Thx. BSD is fine for this project

**Comment by 304NotModified** [comment]
Only the owner, @Xharze can fix this

**Comment by 304NotModified** [comment]
note license file fixed.
