### ISSUE TITLE
Known issue: some tests are failing locally

### ISSUE THREAD

**Issue by mikhail-barg** [NLog/NLog.Windows.Forms#21]
See #14: we have 
- `CustomRowColoringTest`, 
- `CustomWordRowColoringTest`, 
- `NoColoringTest`
- and `SimpleRichTextBoxTargetTest` 
  working on AppVeyor, but failing locally (xunit 1,2; win 10 x64) because of font/font size tags.

Either this is because of some RTB control differences between windows versions, or because of some OS settings. It's also not clear how to properly fix the tests.

Anyway, while they are failing it's good to have the list here, so developers would not worry of broken tests.

**Comment by 304NotModified** [comment]
Good idea to create this github issue. :)
