### ISSUE TITLE
latest nlog do not compatible

### ISSUE THREAD

**Issue by gitlsl** [NLog/NLog.Windows.Forms#27]
Error Error initializing target 'RichTextBox Target[rtb]'. Exception: NLog.NLogRuntimeException: NLog.Windows.Forms.RichTextBoxTarget.allLayouts is null. Call base.InitializeTarget() in NLog.Windows.Forms.RichTextBoxTarget
   在 NLog.Targets.Target.Initialize(LoggingConfiguration configuration)

after I update to latest nlog it broken..

this is my config

    <target xsi:type="RichTextBox"
            name="rtb" 
            layout="${date:format=MM-dd HH\:mm\:ss}|${uppercase:${level}}|${logger}|${message}"
            controlName="richTextBox1" 
            formName="Form1"
            useDefaultRowColoringRules ="true" maxLines="200" autoScroll="true"/>

**Comment by 304NotModified** [comment]
Is throwExceptions set to true?

**Comment by gitlsl** [comment]
@304NotModified   when I update latest nlog ,   richtextbox Target   has no log, I set  throwExceptions  true firstly then  see the error, so I create this issue

**Comment by 304NotModified** [comment]
OK thanks for the feedback!

**Comment by 304NotModified** [comment]
Closed by #28 
Thanks @mikhail-barg !

**Comment by 304NotModified** [comment]
online!

https://www.nuget.org/packages/NLog.Windows.Forms/4.2.2
