### ISSUE TITLE
Target support for .net core 3.0

### ISSUE THREAD

**Issue by Logerfo** [NLog/NLog.Windows.Forms#39]
> Warning	NU1701	Package 'NLog.Windows.Forms 4.2.3' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.

**Comment by 304NotModified** [comment]
PR would be great for this!

**Comment by 304NotModified** [comment]
Hi!

I've created a port locally. I think work, but haven't got it working on the CI

The package: (remove `.zip` from the name)

[NLog.Windows.Forms.4.3.0-beta1.nupkg.zip](https://github.com/NLog/NLog.Windows.Forms/files/3298888/NLog.Windows.Forms.4.3.0-beta1.nupkg.zip)

**Comment by Logerfo** [comment]
Thanks! I'm currently postponing migrating to .NET Core 3.0 to a couple of months, but will try it out as soon as I get back to it.

**Comment by 304NotModified** [comment]
:+1: please let me know if you have any feedback (positive and/or negative)

**Comment by 304NotModified** [comment]
Unfortunately I found an issue, https://github.com/NLog/NLog.Windows.Forms/pull/42#issuecomment-521434661
