### ISSUE TITLE
Sign assembly NLog.Windows.Forms (NLog is signed)

### ISSUE THREAD

**Issue by Sire** [NLog/NLog.Windows.Forms#4]
Please sign the assembly, just like the NLog assembly. Thanks!

**Comment by 304NotModified** [comment]
We are thinking of this, but we not convised.

* http://strongnamingconsideredharmful.com
* http://jeremydmiller.com/2014/04/28/fubumvc-lessons-learned-strong-naming-woes-and-workarounds/
* http://code972.com/blog/2014/04/68-ditching-strong-naming-for-lucene-net

**Comment by Sire** [comment]
I did not know that signing gave NO security at all. Then I see no need for signing NLog at all, or our application that uses it. Thanks for the links!

**Comment by 304NotModified** [comment]
FYI: After all, this has been fixed with version 4.0.
