### ISSUE TITLE
FormControl not found when calling .NET app via Windows Shell

### ISSUE THREAD

**Issue by nmagoncalves** [NLog/NLog.Windows.Forms#48]
I have a C# .NET 4.6.2 desktop app that works great in a normal execution of the *.exe. I recently had the need to call the *.exe file inside Excel VBA via Shell and i notice that NLog was not able to recognize the FormControl returning the error "(...) target cannot be found".

This is my config:

```xml
  <targets>
      <target name="file" xsi:type="File" fileName="C:/logs/${shortdate}.log"  layout="${longdate} > ${logger}|${level}|${message}${exception:format=tostring}"/>
      <target name="control" xsi:type="FormControl" controlName="textBox1" formName="Form1" layout="${longdate}  >  ${message}${exception:format=tostring}" />
  </targets>
  <rules>
    <logger name="*" minlevel="Warn" writeTo="file" />
    <logger name="*" level="Info" writeTo="control" />
  </rules>

**Comment by 304NotModified** [comment]
What you could try is adding:

```
  <extensions> 
    <add assembly="NLog.Windows.Forms"/> 
  </extensions> 
```

to your nlog.config (after `<Nlog ...>)


Otherwise, please check the [internal log](https://github.com/NLog/NLog/wiki/Internal-logging)

**Comment by nmagoncalves** [comment]
Perfect! That resolved the problem! Thank you.
