### ISSUE TITLE
RichTextBoxTarget is not working properly in multiple TabPages

### ISSUE THREAD

**Issue by zouyaoji** [NLog/NLog.Windows.Forms#51]
I want each tabpage to output a log file separately, but I found that the work is not working properly, please download the attachment I uploaded, it should be able to reproduce two problems:
(1) Always open a new window to output to RichTextbox.
(2) Switch to the second page and the window will disappear.

[WindowsFormsApp1.zip](https://github.com/NLog/NLog.Windows.Forms/files/3575097/WindowsFormsApp1.zip)

**Comment by zouyaoji** [comment]
ah..Initializing RichTextBoxTarget in Form1_Load works fine.

But it doesn't work in TabFormControl of DevExpress...

**Comment by zouyaoji** [comment]
Finally, I found the control I needed by rewriting the FindControl method, thank you.

**Comment by 304NotModified** [comment]
I'm glad is has been resolved 👍
