### ISSUE TITLE
Dynamic attachment to RichTextBoxes

### ISSUE THREAD

**Issue by mikhail-barg** [NLog/NLog.Windows.Forms#6]
There's an issue with RichTextBox target described in https://github.com/NLog/NLog/issues/133 in 2012. The essence of the problem is that  RichTextBox target attempts to attach to it's control at initialization, and if it can't find the control, it creates a separate form. This imposes very strict restriction of not accessing any NLog code before all referenced controls are created. 

Other solution is to dynamically update logging configuration on creation/deletion of controls which requires writing a lot of boilerplate code, (see my response to https://github.com/NLog/NLog/issues/133).

I've come with some compromise solution which I'd like to share. For our projects I've created another target totally based on RichTextBoxTarget code with the following modifications:

* Removed everything related creation of custom form in case specified control is not found during `InitializeTarget()`.
* Allowed `TargetRichTextBox` property to be `null` if it's not found.
* Added a check for `TargetRichTextBox` property not being `null` in the beginning of `Write(...)`.
* And added static `RegisterTextBox()`/`UnregisterTextBox()` so that it is possible to notify targets when controls appear/disappear.

The full code is here: https://gist.github.com/mikhail-barg/a9df4732868272cd9de5

This way the target could be specified in the NLog.config just as regular RichTextBox target, and only change in the application code would be to add registration/unregistration code for controls in proper places:

```c#
public Form1()
{
    InitializeComponent();
    RichTextBoxExtTarget.RegisterTextBox(this.richTextBoxLog);
    RichTextBoxExtTarget.RegisterTextBox(this.richTextBoxLogError);
}

private void Form1_FormClosed(object sender, FormClosedEventArgs e)
{
    RichTextBoxExtTarget.UnregisterTextBox(this.richTextBoxLog);
    RichTextBoxExtTarget.UnregisterTextBox(this.richTextBoxLogError);
}
```

This could probably be done automatically by creating a RichTextBox control descendant, but this looks like an overkill to me.

So, what do you think of my proposal? I've been using RichTextBoxTarget for 4 years now and never had any use for the auto-form creation, but on contrary - always had to juggle with initialization order to prevent it from appearing.

**Comment by 304NotModified** [comment]
Hi, 

Can you make a PR for this? It's then easier to discuss the changes and to check the impact.

Please try to keep the code as much backwards compatible as possible.

**Comment by mikhail-barg** [comment]
Sure, I'll prepare a PR, but meanwhile I'd like to know your opinion on a preferred way to make the change. I see the following options:
* completely change old behaviour - no custom form creation (most straightforward, but not backward-compatible in terms of behaviour);
* make new behaviour optional via some boolean parameter like `dontCreateCustomFormIfNotFound` (clumsy and a bit bloated but backward-compatible);
* create a separate target inheriting from existing, or from newly-introduced common ancestor (looks like an overkill).

**Comment by 304NotModified** [comment]
We think backwards-compatibility is very important, so I'm doubting between 2 and 3.

I see a lot of changes in the gist. If we can't narrow down the changes, then 3 is preferred, otherwise 2.

**Comment by mikhail-barg** [comment]
OK, I'll try to stick with the 2 first, thanks for the guidance!

**Comment by 304NotModified** [comment]
I changed a lot in the code, so after the merge #8, it would be wise to update before start ;)

**Comment by mikhail-barg** [comment]
Oops, just noticed your previous comment. Would it merge this way, or should I revert and start from scratch?

**Comment by 304NotModified** [comment]
We have no preference :)

**Comment by mikhail-barg** [comment]
Closing this as everything was solved in the PR #9

**Comment by 304NotModified** [comment]
@mikhail-barg 

4.1 has been released! I added also your name to the NuGet package: https://www.nuget.org/packages/NLog.Windows.Forms/4.1.0

Also I added you as collaborator to the repository, as I'm very happy with the collaboration, your good ideas and contributions! I assume you will keep everything working ;)

**Comment by mikhail-barg** [comment]
Thanks! I'm glad the Reinitialize* code got in release!
Regarding being a collaborator — it feels like a heavy responsibility and I'm not sure I'll be able to keep up, but we'll see. Thanks anyway!
