### ISSUE TITLE
Missing source package on NuGet

### ISSUE THREAD

**Issue by Worldexe** [NLog/NLog.Windows.Forms#68]
There is no source package on https://www.nuget.org/packages/NLog.Windows.Forms/.
Can we get it please? It would make debugging rare problems much easier.

**Comment by 304NotModified** [comment]
Hey! I will check if I could add this. I have to check if I have to merge first (#42) - which is large

**Comment by 304NotModified** [comment]
It was uploaded (see [log](https://ci.appveyor.com/project/nlog/nlog-windows-forms/builds/25345723), but I gives now this error


![image](https://user-images.githubusercontent.com/5808377/112882237-fd294300-90cc-11eb-8957-d040d7c63237.png)

**Comment by 304NotModified** [comment]
ow this is https://github.com/NLog/NLog.Windows.Forms/issues/62

**Comment by 304NotModified** [comment]
@Worldexe 4.4 is now live with debug symbols, sourcelink and deterministic build :) 

![image](https://user-images.githubusercontent.com/5808377/112893748-5f894000-90db-11eb-878a-d995794cf892.png)

https://www.nuget.org/packages/NLog.Windows.Forms/4.4.0
