### ISSUE TITLE
RichTextBoxTarget: maxLines + RichTextBox.WordWrap issue

### ISSUE THREAD

**Issue by balticer** [NLog/NLog.Windows.Forms#7]
Hi,

i'm using NLog 4.1.0.0 and NLog.Windows.Forms 2.0.0.0. If WordWrap is enabled for a RichTextBox and the lines are wrapped, then strange behavior occurs. Old lines are not removed and the RichTextBox fills up endless.

Releated stuff:
https://msdn.microsoft.com/en-us/library/system.windows.forms.richtextbox.getlinefromcharindex.aspx

regards
Kai

**Comment by kevindaub** [comment]
Related to https://github.com/NLog/NLog/issues/891

**Comment by 304NotModified** [comment]
Thanks for the report! This is almost fixed.

Also thanks @kevindaub

**Comment by 304NotModified** [comment]
This has been released! Version 2.1.0

**Comment by 304NotModified** [comment]
Thanks for the report and fix!
