### ISSUE TITLE
No RowColor for RichTextBoxTarget when LeftToRight.Yes set

### ISSUE THREAD

**Issue by vyuzhanin** [NLog/NLog.Windows.Forms#83]
**Nlog:** 4.7.10
**NLog.Windows.Forms**: 4.4.0
**Platform:** net5.0-windows

Here is my code example based on [this example](https://nlog-project.org/documentation/v2.0.1/html/T_NLog_Targets_RichTextBoxTarget.htm):
```C#
            RichTextBox rtbLogs = new RichTextBox();
            rtbLogs.Dock = DockStyle.Fill;
            rtbLogs.Name = "rtbLogs";
            rtbLogs.ReadOnly = true;
            rtbLogs.BorderStyle = BorderStyle.FixedSingle;
            rtbLogs.BackColor = Color.White;

            this.Controls.Add(rtbLogs);

            RichTextBoxTarget target = new RichTextBoxTarget();
            target.Layout = "${longdate} [${threadname:whenEmpty=${threadid}}] ${uppercase:${level}} ${message:withException=true} ${all-event-properties}";
            target.TargetRichTextBox = rtbLogs;
            target.UseDefaultRowColoringRules = true;
            NLog.Config.SimpleConfigurator.ConfigureForTargetLogging(target, NLog.LogLevel.Trace);
```

It hightlights the text fine: 
![image](https://user-images.githubusercontent.com/596514/121778311-050e6480-cb9f-11eb-9368-f39fffbbea1c.png)

But when I try to set **RightToLeft = RightToLeft.Yes** for main form after I initialized the RichTextBoxTarget then the hightlight is gone. And it shows just a regular text:
![image](https://user-images.githubusercontent.com/596514/121778422-777f4480-cb9f-11eb-943d-cd6580d0f793.png)

**Comment by vyuzhanin** [comment]
I've tried to use custom [RowColorRules](https://nlog-project.org/documentation/v2.0.1/html/P_NLog_Targets_RichTextBoxTarget_RowColoringRules.htm) but the same result

**Comment by 304NotModified** [comment]
This seems to be fixed in Version 5!

![image](https://user-images.githubusercontent.com/5808377/170327134-66c58f14-ac8d-42c1-b8ea-56ce911d44ee.png)
