### ISSUE TITLE
PublishSingleFile causes Target symbol-name is unknown: 'RichTextBox'

### ISSUE THREAD

**Issue by lionengine123** [NLog/NLog.Windows.Forms#99]
Hello,

I use NLog.Windows.Forms (version 4.5.0).
Whenever a Project is published with this property:

`<PublishSingleFile>true</PublishSingleFile>`

I get such an error: (internalLogfile.log)

```
Info Message Template Auto Format enabled
Info Adding target FileTarget(Name=logfile)
Warn Error has been raised. Exception: NLog.NLogConfigurationException: Failed to create Target of type: RichTextBox
 ---> System.ArgumentException: Target symbol-name is unknown: 'RichTextBox'
   at NLog.Config.Factory`2.CreateInstance(String itemName)
   at NLog.Config.LoggingConfigurationParser.FactoryCreateInstance[T](String classType, INamedItemFactory`2 factory)
   --- End of inner exception stack trace ---
Warn Error has been raised. Exception: NLog.NLogConfigurationException: Failed to create Target of type: RichTextBox
 ---> System.ArgumentException: Target symbol-name is unknown: 'RichTextBox'
   at NLog.Config.Factory`2.CreateInstance(String itemName)
   at NLog.Config.LoggingConfigurationParser.FactoryCreateInstance[T](String classType, INamedItemFactory`2 factory)
   --- End of inner exception stack trace ---
Warn Error has been raised. Exception: NLog.NLogConfigurationException: Target 'warningControl' not found for logging rule: *.
Warn Error has been raised. Exception: NLog.NLogConfigurationException: Target 'logControl' not found for logging rule: *.
Info Validating config: TargetNames=logfile, ConfigItems=23, FilePath=D:\development\branches\EFA_10_5\realtime\Solutions\DDIP\Applications\Mdv.DDIP.BatchWork.GUI\bin\release\win-x64\publish\NLog.config
Info Configuration initialized.
Info NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: . Product version: . GlobalAssemblyCache: False
Info Executing ReInitializeAllTextboxes for Form Mdv.Realtime.BatchWork.GUI.MainWindow, Text: DDIP v.10.5.8.1 Batch work GUI [new]
Info Configuring from an XML element in D:\development\branches\EFA_10_5\realtime\Solutions\DDIP\Applications\Mdv.DDIP.BatchWork.GUI\bin\release\win-x64\publish\NLog.config...
Info Message Template Auto Format enabled
Info Adding target FileTarget(Name=logfile)
Warn Error has been raised. Exception: NLog.NLogConfigurationException: Failed to create Target of type: RichTextBox
 ---> System.ArgumentException: Target symbol-name is unknown: 'RichTextBox'
   at NLog.Config.Factory`2.CreateInstance(String itemName)
   at NLog.Config.LoggingConfigurationParser.FactoryCreateInstance[T](String classType, INamedItemFactory`2 factory)
   --- End of inner exception stack trace ---
Warn Error has been raised. Exception: NLog.NLogConfigurationException: Failed to create Target of type: RichTextBox
 ---> System.ArgumentException: Target symbol-name is unknown: 'RichTextBox'
   at NLog.Config.Factory`2.CreateInstance(String itemName)
   at NLog.Config.LoggingConfigurationParser.FactoryCreateInstance[T](String classType, INamedItemFactory`2 factory)
   --- End of inner exception stack trace ---
Warn Error has been raised. Exception: NLog.NLogConfigurationException: Target 'warningControl' not found for logging rule: *.
Warn Error has been raised. Exception: NLog.NLogConfigurationException: Target 'logControl' not found for logging rule: *.
Info Validating config: TargetNames=logfile, ConfigItems=23, FilePath=D:\development\branches\EFA_10_5\realtime\Solutions\DDIP\Applications\Mdv.DDIP.BatchWork.GUI\bin\release\win-x64\publish\NLog.config
Info AppDomain Shutting down. LogFactory closing...
Info LogFactory has been closed.

```

I tried the following package constellations:

```
Nlog 5.0.0-rc2
Nlog.Windows.Forms 4.5.0
```

and

```
NLog 4.7.0
Nlog.Windows.Forms 4.5.0-rc1
```

In case I build the project without this PublishSingleFile property, the logging into RichTextBox works fine.

**Comment by 304NotModified** [comment]
Hi,

Could you please try this?

https://github.com/nlog/nlog/wiki/Register-your-custom-component#register-nlog-extensions-from-assembly-at-runtime

**Comment by lionengine123** [comment]
I added this one code line at the very beginning of the program.cs main method and exchanged 'myAssembly' with my Assembly name.
However this did not work. It still does not log into the corresponding richtext box when the program is published as single file.

**Comment by snakefoot** [comment]
Maybe try this:

```c#
NLog.LogManager.Setup().SetupExtensions(s => s.RegisterAssembly(typeof(NLog.Windows.Forms.RichTextBoxTarget).Assembly));
```

**Comment by lionengine123** [comment]
yes, this works.

We have 20 Projects and try to keep it as 'clean' as possible. In case it would be possible to fix the issue within the future version of nlog windows forms library, it would be great.

System.Configuration.ConfigurationManager had a similiar problem and fixed it with version 6.0.0 btw.

**Comment by snakefoot** [comment]
Does your `NLog.config` include:

```xml
<nlog> 
  <extensions> 
    <add assembly="NLog.Windows.Forms"/> 
  </extensions> 
```

**Comment by lionengine123** [comment]
No, my nlog.config does not include any extension entries.

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by snakefoot** [comment]
> No, my nlog.config does not include any extension entries.

You can remove the explict `RegisterAssembly` if you update your NLog.config to include `<extensions>`-section.

Notice NLog 5.0 will no longer automatically scan and load NLog-extension-assemblies. Instead NLog-extension-assemblies must always be explicitly specified. But NLog 5.0 also introduces support for specifying assembly-name in target-type:

```xml
<target xsi:type="RichTextBox, NLog.Windows.Forms" name="myRichTextBox" ... />
```

**Comment by lionengine123** [comment]
> Have you tried to explicit include the Assembly in your `NLog.config`:
> 
> ```
> <nlog> 
>   <extensions> 
>     <add assembly="NLog.Windows.Forms"/> 
>   </extensions> 
> ```

Thank you this also works. (So no code changes aka 'RegisterAssembly' necessary.

**Comment by lionengine123** [comment]
> You can replace the explict `RegisterAssembly` in source-code with `<extensions>`-section in NLog.config.
> 
> Notice NLog 5.0 will [no longer scan and load NLog-extension-assemblies](https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html#nlog-extensions-assemblies-will-not-load-automatically) automatically. Instead NLog-extension-assemblies must always be explicitly specified. But NLog 5.0 also introduces support for specifying assembly-name in target-type:
> 
> ```
> <target xsi:type="RichTextBox, NLog.Windows.Forms" name="myRichTextBox" ... />
> ```

Adding 
`<target xsi:type="RichTextBox, NLog.Windows.Forms" name="myRichTextBox" ... />`

was not sufficient (/ is not needed) when publishing as single file. 
There also needs to be this declaration:

`<extensions> 
    <add assembly="NLog.Windows.Forms"/> 
  </extensions> `

(Tested with 5.0.0-rc2)

**Comment by snakefoot** [comment]
NLog InternalLogger looks like this on my machine, and it just works with NLog 5.0-RC2:
```
Info Message Template Auto Format enabled
Debug ScanAssembly('NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
Info Loading assembly: NLog.Windows.Forms
Debug ScanAssembly('NLog.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
```

**Comment by lionengine123** [comment]
This thread is all about publishing as single file.
Did you publish your application as Single file?

**Comment by lionengine123** [comment]
Thanks,
I was just asking because the program behaviour differs from our application.
we also build with 
`dotnet publish -c:Release`

However we have: (Net5.0)

`<TargetFramework>net5.0-windows</TargetFramework>`
and also usually
`<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>`

Perhaps that's where the different behaviour comes from.
As
`<target xsi:type="RichTextBox, NLog.Windows.Forms" ... />`
doesn't work for us.


Your answer:

> Have you tried to explicit include the Assembly in your `NLog.config`:
> 
> ```
> <nlog> 
>   <extensions> 
>     <add assembly="NLog.Windows.Forms"/> 
>   </extensions> 
> ```

is already our solution and solves the problem on our side.

**Comment by lionengine123** [comment]
In your Testsetting I realized you are not using a controlName. Do you log into a separate Logging Window?
We are logging into an existing richtextbox, which is a big difference ...

**Comment by snakefoot** [comment]
Think your questions are beyond my skill-set when it comes to the `NLog.Windows.Forms`-package.

I was mostly interested in whether `xsi:type="RichTextBox, NLog.Windows.Forms"` worked with NLog 5.0 and PublishSingleFile=true (And it did for me).

And yes when using NLog 4.7, then it will only work with:
```xml
<nlog> 
  <extensions> 
    <add assembly="NLog.Windows.Forms"/> 
  </extensions>
````

**Comment by snakefoot** [comment]
Closing issue as answered due to inactivity
